proxy:
  image: proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=13.64.170.115
    - NGINX_PROXY=http://identidock:9000

identidock:
  image: vanger69/identidock:0.1
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:latest
